name: Run unit tests

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create virtual environment
        run: python -m virtualenv venv
        
      - name: Activate virtual environment
        run: source venv/bin/activate

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Run unit tests
        run: |
          python -m unittest discover
